### PR TITLE
Update patch version for security

### PR DESCRIPTION
**Pull request by JackHowa**
- Ran yarn, yarn lint, and yarn test
- Updated the patch version to release #29 

**Learn more about contributing:** [CONTRIBUTING.md](./contributing.md)

### CODE REVIEW

**Comment by JackHowa** [comment]
Huh seeing this error in the ci: 

```
#!/bin/sh -eo pipefail
# ERROR IN CONFIG FILE:
# [#] required key [jobs] not found
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false

**Comment by JackHowa** [comment]
@MattMcFarland did you have time for a publish as well? sorry to bother #29

**Comment by JackHowa** [comment]
@conartist6 you don't have publish rights, I'm assuming?

**Comment by conartist6** [comment]
I don't believe so no.

**Comment by JackHowa** [comment]
Thanks @MattMcFarland -- let me know if I can help further. look forward to next version!  https://www.npmjs.com/package/esdoc2

**Comment by JackHowa** [comment]
let me know about the publish @MattMcFarland -- sorry to bother on this, didn't see it in npm

**Pull request merged**
